# Generated by Django 4.0.6 on 2022-07-22 06:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('exchange_currency', models.CharField(max_length=3)),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_currency', models.CharField(max_length=3)),
                ('debit_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_currency', models.CharField(max_length=3)),
                ('credit_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('updated_by', models.TextField()),
                ('credit_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='requests_created', to='api.wallet')),
                ('debit_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_requests_created', to='api.wallet')),
                ('wallet_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=3)),
                ('currency_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.wallet')),
            ],
        ),
    ]
